DB_ADAPTER_PROD:            postgresql
DB_DATABASE_PROD:           name
DB_ENCODING_PROD:           unicode
DB_HOST_PROD:               host.com
DB_PASSWORD_PROD:           password
DB_PORT_PROD:               5432
DB_USERNAME_PROD:           username
GITHUB_APP_ID:              123
GITHUB_APP_SECRET:          abc123
GITHUB_APP_ID_DEV:          123
GITHUB_APP_SECRET_DEV:      abc123
GITHUB_CALLBACK_URI:        http://yourapp.com/auth/callback
GITHUB_USERNAME:            johndoe
GITHUB_TOKEN:               abc123
NEW_RELIC_APP_NAME:         Appname
NEW_RELIC_LICENSE_KEY:      abc123
NEW_RELIC_LOG:              stdout
ROOT_URL:                   http://yourapp.com/
SECRET_HASH:                abc123